### ISSUE TITLE
MVP 0.1

### ISSUE THREAD

**Issue by mihok** [minimalchat/operator-app#3]
MVP Plan for the Operator App.

Following the wireframe from our [Design Documentation](https://github.com/minimalchat/mnml-operator-app/wiki/Design-Documentation) the MVP push is to get the basic layout, and initial functionality.

![minimal chat - operator design document](https://cloud.githubusercontent.com/assets/563301/23826150/2278628c-0664-11e7-8f05-4f4fbfc57da2.png)

# 0.1
### Global
- [x] Basic 3-pane layout (operator menu, chat list, active chat)
- [x] On first load, look for `config.json` in directory or create it: 
   - [x] Use config.json to find API URI, *or* ask using simple [window.prompt()](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) window to ask for a API Server URI or use `config.json` (#10)
   - [x] Use config.json to find operator username/id *or* ask for it with simple [window.prompt()](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) (If config.json doesnt exist) (#11)
- [x] On load, create socket connection with API server (#12)
- [x] On load, pull available chats from API server `/api/chats` endpoint (#4)
- [x] Incoming chats from socket adds to available chats (i.e. someone browses to the client website while Operator app is open) (#13)

### Operator Menu
- [x] Hide *or* grey out "Assigned to Me (1)" (#14)
- [x] Update "Open (COUNT)" based on number of chats *without* `"open": false` (#16)
- [x] On click filter "All" show all chats in **Chat List** regardless of `"open": true/false` value (#18)
- [x] On click filter "Open (3)" show only chats in **Chat List** with `"open": true` (#17)
- [x] On click filter "Closed" show only chats in **Chat List** with `"open": false` (#19)

### Chat List
- [x] Searching filters the current list of visible chats (#20)
- [x] On clicking a chat in the list, update active chat ID (#21)
- [x] Order chat list based on `updated_time` (#22)

### Active Chat
- [x] On new active chat ID:
   - [x] Pull historical messages from API server `api/chat/:CHAT_ID/messages` endpoint (#23)
- [x] Send and recieve messages through socket connection (#24)
- [x] On click active chat "Mark as done" icon, updates `"open": false` (#25)
- [x] Hide *or* grey out "Assign to other" for now (#15)

**Comment by teesloane** [comment]
Feedback:

## Operation Menu section
> Update "Open (COUNT)" based on number of chats without "open": false
- struct question - what is this `open` boolean stored on? 

## Chat List section
> On click chat **from**, update active chat ID
- use of word `from` confuses me? missing a word? 

## General Q's
- anything with text like "Hide or grey out "Assign to other" for now"
  - are these features that are just not available for now?

**Comment by mihok** [comment]
- `open` will likely live on the Chat object, but hasnt been implemented yet
- Typo, ill fix.
- Correct, I think it adds a level of complexity (assigning chats to operators) that isnt necessary for 0.1 MVP
