### ISSUE TITLE
MVP 0.3

### ISSUE THREAD

**Issue by mihok** [minimalchat/operator-app#89]
The focus for 0.3 is around getting things set up for the Chat as a Service

# Milestones

- [ ] Allow user to change Operator avatar
- [ ] Allow user to change Site Visitor in client list
- [ ] Either Operator or Daemon to send Email notification of new unread messages?
- [ ] Either Operator or Daemon to allow user to setup Webhook URL for new unread messages?
